FROM python:2.7.18-slim-buster

RUN apt-get update && \
    apt-get install -y gcc openssl libssl-dev libffi-dev && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade setuptools --user

